name: Check my commit streaks

on:
    push:
        branches: [main]
    schedule:
        - cron: 0 0 * * *

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 15.x

            - run: yarn --frozen-lockfile
            - run: yarn run serve:twilio
              env:
                  TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
                  TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
                  TWILIO_PHONE_NO: ${{ secrets.TWILIO_PHONE_NO }}
                  RECIPIENT_PHONE_NO: ${{ secrets.RECIPIENT_PHONE_NO }}
